name: Tag release

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'

      - name: Get commit tag
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagname

      - name: Use tag
        run: |
          echo "Tag Output: ${{steps.tagname.outputs.tag}}"
          echo "RefName: ${{github.ref_name}}"
          ls
          echo "Git describe: $(git describe --tags)"
